### ISSUE TITLE
Support for HomeAssistant Plugin

### ISSUE THREAD

**Issue by wes1993** [madchicken/homebridge-comelit-icona#3]
Hello,
there is a way to add support for HomeAssistant Plugin or expose an http uri to call for open the gate?

Best Regards
Stefano

**Comment by madchicken** [comment]
Building a simple web server that exposes an URL to open a door should be fairly easy since the plugin itself uses the Comelit Client from my other project.
I honestly don't know how HA works, but I saw that someone was able to integrate my client here https://community.home-assistant.io/t/comelit-video-intercom/15128/19
